contact_links:
  - name: ğŸ“š Documentation
    url: https://v3.nuxtjs.org/
    about: Check documentation for usage
  - name: ğŸ’¬ Discussions
    url: https://github.com/nuxt/framework/discussions
    about: Use discussions if you have an idea for improvement and asking questions
  - name: ğŸ› Known Bugs
    url: https://github.com/nuxt/framework/issues?q=is%3Aopen+is%3Aissue+label%3Abug
    about: Check for open bugs

